controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    artebot_diff_controller:
      type: diff_drive_controller/DiffDriveController

    artebot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

artebot_diff_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.123
    wheel_radius: 0.022

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0

    #odom_frame_id: odom
    base_frame_id: base_link

    #pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    #twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    use_stamped_vel: false

    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.0
    linear.x.min_velocity: 0.0
    linear.x.max_acceleration: 0.0
    linear.x.min_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.0
    angular.z.min_velocity: 0.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

# artebot_joint_state_broadcaster:
#   ros__parameters: